export interface Course {
  id: string;
  title: string;
  channel: string;
  views: string;
  likes: string;
  duration: string;
  level: string;
  matchScore: number;
  url: string;
  topics: string[];
}

export const COURSES_BY_ROLE: Record<string, Course[]> = {
  "Frontend Development": [
    {
      id: "fe1",
      title: "React Full Course 2026 – Build Real Projects",
      channel: "Traversy Media",
      views: "2.1M",
      likes: "89K",
      duration: "12h 30m",
      level: "Beginner",
      matchScore: 98,
      url: "https://www.youtube.com/watch?v=bMknfKXIFA8",
      topics: ["React", "State Management", "Hooks"],
    },
    {
      id: "fe2",
      title: "Mastering Next.js 15 App Router",
      channel: "Fireship",
      views: "1.2M",
      likes: "55K",
      duration: "4h 15m",
      level: "Intermediate",
      matchScore: 95,
      url: "https://www.youtube.com/watch?v=wm5gMKuwSYk",
      topics: ["Next.js", "SSR", "SEO"],
    },
    {
      id: "fe3",
      title: "CSS Grid and Flexbox Masterclass",
      channel: "Kevin Powell",
      views: "850K",
      likes: "42K",
      duration: "3h 45m",
      level: "Beginner",
      matchScore: 92,
      url: "https://www.youtube.com/watch?v=rg7Fvvl3zuU",
      topics: ["Layout", "CSS", "UI Design"],
    },
  ],
  "Backend Development": [
    {
      id: "be1",
      title: "Node.js Backend Masterclass – Complete Guide",
      channel: "Programming with Mosh",
      views: "3.5M",
      likes: "120K",
      duration: "15h 20m",
      level: "Beginner",
      matchScore: 97,
      url: "https://www.youtube.com/watch?v=TlB_eWDSMt4",
      topics: ["Node.js", "Express", "MongoDB"],
    },
    {
      id: "be2",
      title: "PostgreSQL Database Design",
      channel: "The Net Ninja",
      views: "1.1M",
      likes: "48K",
      duration: "6h 10m",
      level: "Intermediate",
      matchScore: 94,
      url: "https://www.youtube.com/watch?v=qw--VvlkR60",
      topics: ["SQL", "Database Design", "Postgre"],
    },
    {
      id: "be3",
      title: "Building Microservices with Go",
      channel: "FreeCodeCamp",
      views: "720K",
      likes: "35K",
      duration: "8h 45m",
      level: "Advanced",
      matchScore: 89,
      url: "https://www.youtube.com/watch?v=VzBGi_naiMQ",
      topics: ["Go", "Microservices", "gRPC"],
    },
  ],
  "Full Stack Development": [
    {
      id: "fs1",
      title: "T3 Stack Tutorial – Full Stack Next.js",
      channel: "Theo - t3.gg",
      views: "450K",
      likes: "25K",
      duration: "5h 30m",
      level: "Intermediate",
      matchScore: 96,
      url: "https://www.youtube.com/watch?v=Y8k-X-1A3-g",
      topics: ["Next.js", "tRPC", "Prisma"],
    },
    {
      id: "fs2",
      title: "Full Stack SaaS Project – React, Node, Postgres",
      channel: "JavaScript Mastery",
      views: "1.8M",
      likes: "95K",
      duration: "10h 15m",
      level: "Intermediate",
      matchScore: 93,
      url: "https://www.youtube.com/watch?v=mYy-vHhI704",
      topics: ["SaaS", "Fullstack", "Deployment"],
    },
  ],
  "Data Science": [
    {
      id: "ds1",
      title: "Data Science for Beginners – Python Full Course",
      channel: "FreeCodeCamp",
      views: "5.2M",
      likes: "210K",
      duration: "12h 00m",
      level: "Beginner",
      matchScore: 98,
      url: "https://www.youtube.com/watch?v=ua-CiDNNj30",
      topics: ["Python", "Pandas", "Analysis"],
    },
    {
      id: "ds2",
      title: "Probability and Statistics for Data Science",
      channel: "Khan Academy",
      views: "2.4M",
      likes: "85K",
      duration: "20h 30m",
      level: "Beginner",
      matchScore: 95,
      url: "https://www.youtube.com/watch?v=uhxtUt_-GyM",
      topics: ["Statistics", "Probability", "Math"],
    },
  ],
  "Machine Learning": [
    {
      id: "ml1",
      title: "Machine Learning with Python & Scikit-Learn",
      channel: "Sentdex",
      views: "4.1M",
      likes: "150K",
      duration: "18h 45m",
      level: "Intermediate",
      matchScore: 96,
      url: "https://www.youtube.com/watch?v=OGxgnH8y2NM",
      topics: ["ML", "Regression", "SVM"],
    },
    {
      id: "ml2",
      title: "Deep Learning Crash Course for Beginners",
      channel: "Krish Naik",
      views: "1.5M",
      likes: "72K",
      duration: "7h 15m",
      level: "Intermediate",
      matchScore: 92,
      url: "https://www.youtube.com/watch?v=aircAruvnKk",
      topics: ["Deep Learning", "Neural Networks", "PyTorch"],
    },
  ],
  "DevOps": [
    {
      id: "do1",
      title: "DevOps Roadmap 2026 – Learn the Full Lifecycle",
      channel: "TechWorld with Nana",
      views: "1.5M",
      likes: "65K",
      duration: "6h 45m",
      level: "Beginner",
      matchScore: 99,
      url: "https://www.youtube.com/watch?v=XRGxuX8W720",
      topics: ["Docker", "Kubernetes", "CI/CD"],
    },
    {
      id: "do2",
      title: "Infrastructure as Code with Terraform",
      channel: "Hieu Nguyen",
      views: "250K",
      likes: "12K",
      duration: "4h 20m",
      level: "Intermediate",
      matchScore: 94,
      url: "https://www.youtube.com/watch?v=7xngnjfIlK8",
      topics: ["IaC", "Terraform", "Cloud"],
    },
  ],
  "Mobile Development": [
    {
      id: "md1",
      title: "React Native Portfolio App – Full Course",
      channel: "Sonny Sangha",
      views: "890K",
      likes: "45K",
      duration: "8h 10m",
      level: "Beginner",
      matchScore: 95,
      url: "https://www.youtube.com/watch?v=0-S5a0eXPoc",
      topics: ["React Native", "Expo", "Navigation"],
    },
    {
      id: "md2",
      title: "Flutter & Firebase for Beginners",
      channel: "The Net Ninja",
      views: "1.2M",
      likes: "58K",
      duration: "7h 30m",
      level: "Beginner",
      matchScore: 92,
      url: "https://www.youtube.com/watch?v=sfA3NWnVPZg",
      topics: ["Flutter", "Dart", "Firebase"],
    },
  ],
  "Cloud Computing": [
    {
      id: "cc1",
      title: "AWS Certified Solutions Architect Course",
      channel: "DigitalCloud Training",
      views: "1.2M",
      likes: "52K",
      duration: "10h 45m",
      level: "Beginner",
      matchScore: 97,
      url: "https://www.youtube.com/watch?v=SOTamWNgDKc",
      topics: ["AWS", "IAM", "VPC"],
    },
    {
      id: "cc2",
      title: "Google Cloud Platform Fundamentals",
      channel: "Google Cloud Tech",
      views: "450K",
      likes: "25K",
      duration: "5h 15m",
      level: "Beginner",
      matchScore: 94,
      url: "https://www.youtube.com/watch?v=4D3X6Z9Z6O8",
      topics: ["GCP", "Compute Engine", "Storage"],
    },
  ],
  "Cybersecurity": [
    {
      id: "cy1",
      title: "Cybersecurity Full Course for Beginners",
      channel: "Edureka",
      views: "2.8M",
      likes: "105K",
      duration: "12h 20m",
      level: "Beginner",
      matchScore: 98,
      url: "https://www.youtube.com/watch?v=nzj7Wg46ksU",
      topics: ["Ethical Hacking", "Networks", "Cryptography"],
    },
    {
      id: "cy2",
      title: "CompTIA Security+ SY0-701 Full Course",
      channel: "Professor Messer",
      views: "950K",
      likes: "48K",
      duration: "15h 45m",
      level: "Intermediate",
      matchScore: 95,
      url: "https://www.youtube.com/watch?v=9neIT9KC87S",
      topics: ["Governance", "Risk Management", "Compliance"],
    },
  ],
  "UI/UX Design": [
    {
      id: "ui1",
      title: "Figma UI Design Masterclass 2026",
      channel: "DesignCourse",
      views: "1.1M",
      likes: "62K",
      duration: "8h 30m",
      level: "Beginner",
      matchScore: 97,
      url: "https://www.youtube.com/watch?v=FTFaQW9PqM8",
      topics: ["Figma", "Typography", "Color Theory"],
    },
    {
      id: "ui2",
      title: "User Experience (UX) Design Full Course",
      channel: "Flux Academy",
      views: "680K",
      likes: "35K",
      duration: "6h 15m",
      level: "Beginner",
      matchScore: 93,
      url: "https://www.youtube.com/watch?v=68w2VwuzWos",
      topics: ["User Research", "Wireframing", "Prototyping"],
    },
  ],
  "Blockchain": [
    {
      id: "bc1",
      title: "Blockchain Full Course - 12 Hours",
      channel: "Dapp University",
      views: "1.2M",
      likes: "55K",
      duration: "12h 10m",
      level: "Beginner",
      matchScore: 96,
      url: "https://www.youtube.com/watch?v=M576WGiDBdQ",
      topics: ["Solidity", "Ethereum", "Smart Contracts"],
    },
    {
      id: "bc2",
      title: "Web3.js and Ethers.js Tutorial",
      channel: "Patrick Collins",
      views: "750K",
      likes: "38K",
      duration: "5h 45m",
      level: "Intermediate",
      matchScore: 92,
      url: "https://www.youtube.com/watch?v=gyMwXuJrbJQ",
      topics: ["Web3", "Frontend", "DeFi"],
    },
  ],
  "Game Development": [
    {
      id: "gd1",
      title: "Unity Game Development Full Course",
      channel: "Brackeys",
      views: "4.5M",
      likes: "185K",
      duration: "10h 20m",
      level: "Beginner",
      matchScore: 99,
      url: "https://www.youtube.com/watch?v=j48LtUkZRjU",
      topics: ["Unity", "C#", "Game Physics"],
    },
    {
      id: "gd2",
      title: "Unreal Engine 5 Beginner Tutorial",
      channel: "Unreal Engine",
      views: "2.1M",
      likes: "92K",
      duration: "8h 45m",
      level: "Beginner",
      matchScore: 95,
      url: "https://www.youtube.com/watch?v=gQmiqmxPaV0",
      topics: ["Unreal Engine", "Blueprints", "Graphics"],
    },
  ],
};
