export interface Job {
  id: string;
  title: string;
  company: string;
  location: string;
  salary: string;
  type: "Remote" | "Hybrid" | "On-site";
  postedAt: string;
  url: string;
  logo: string;
  matchScore: number;
}

export const FALLBACK_JOBS: Record<string, Job[]> = {
  "Frontend Development": [
    {
      id: "fe-j1",
      title: "Senior Frontend Engineer (React/Next.js)",
      company: "Stripe",
      location: "San Francisco, CA",
      salary: "$160k – $220k",
      type: "Remote",
      postedAt: "2 days ago",
      url: "https://www.linkedin.com/jobs",
      logo: "https://logo.clearbit.com/stripe.com",
      matchScore: 98,
    },
    {
      id: "fe-j2",
      title: "UI Engineer",
      company: "Airbnb",
      location: "San Francisco, CA",
      salary: "$150k – $190k",
      type: "Hybrid",
      postedAt: "1 day ago",
      url: "https://www.linkedin.com/jobs",
      logo: "https://logo.clearbit.com/airbnb.com",
      matchScore: 95,
    },
    {
      id: "fe-j3",
      title: "Frontend Developer (Internal Tools)",
      company: "Slack",
      location: "Vancouver, BC",
      salary: "$130k – $170k",
      type: "Remote",
      postedAt: "4 hours ago",
      url: "https://www.linkedin.com/jobs",
      logo: "https://logo.clearbit.com/slack.com",
      matchScore: 92,
    },
  ],
  "Backend Development": [
    {
      id: "be-j1",
      title: "Backend Infrastructure Engineer",
      company: "Datadog",
      location: "New York, NY",
      salary: "$170k – $230k",
      type: "Remote",
      postedAt: "1 week ago",
      url: "https://www.linkedin.com/jobs",
      logo: "https://logo.clearbit.com/datadog.com",
      matchScore: 97,
    },
    {
      id: "be-j2",
      title: "Staff Software Engineer (Go)",
      company: "Cloudflare",
      location: "Austin, TX",
      salary: "$180k – $250k",
      type: "Hybrid",
      postedAt: "3 days ago",
      url: "https://www.linkedin.com/jobs",
      logo: "https://logo.clearbit.com/cloudflare.com",
      matchScore: 94,
    },
  ],
  "Full Stack Development": [
    {
      id: "fs-j1",
      title: "Full Stack Developer (T3 Stack)",
      company: "Vercel",
      location: "Remote",
      salary: "$140k – $200k",
      type: "Remote",
      postedAt: "12 hours ago",
      url: "https://www.linkedin.com/jobs",
      logo: "https://logo.clearbit.com/vercel.com",
      matchScore: 99,
    },
    {
      id: "fs-j2",
      title: "Product Engineer",
      company: "Linear",
      location: "Seattle, WA",
      salary: "$160k – $210k",
      type: "Remote",
      postedAt: "2 days ago",
      url: "https://www.linkedin.com/jobs",
      logo: "https://logo.clearbit.com/linear.app",
      matchScore: 96,
    },
  ],
  "Data Science": [
    {
      id: "ds-j1",
      title: "Senior Data Scientist",
      company: "Netflix",
      location: "Los Angeles, CA",
      salary: "$200k – $350k",
      type: "On-site",
      postedAt: "5 days ago",
      url: "https://www.linkedin.com/jobs",
      logo: "https://logo.clearbit.com/netflix.com",
      matchScore: 95,
    },
    {
      id: "ds-j2",
      title: "Data Research Analyst",
      company: "OpenAI",
      location: "San Francisco, CA",
      salary: "$180k – $260k",
      type: "Hybrid",
      postedAt: "1 week ago",
      url: "https://www.linkedin.com/jobs",
      logo: "https://logo.clearbit.com/openai.com",
      matchScore: 92,
    },
  ],
  "Machine Learning": [
    {
      id: "ml-j1",
      title: "Machine Learning Engineer",
      company: "Tesla",
      location: "Palo Alto, CA",
      salary: "$170k – $280k",
      type: "On-site",
      postedAt: "3 days ago",
      url: "https://www.linkedin.com/jobs",
      logo: "https://logo.clearbit.com/tesla.com",
      matchScore: 97,
    },
    {
      id: "ml-j2",
      title: "Applied AI Scientist",
      company: "Anthropic",
      location: "San Francisco, CA",
      salary: "$220k – $380k",
      type: "Hybrid",
      postedAt: "2 days ago",
      url: "https://www.linkedin.com/jobs",
      logo: "https://logo.clearbit.com/anthropic.com",
      matchScore: 94,
    },
  ],
  "DevOps": [
    {
      id: "do-j1",
      title: "Site Reliability Engineer",
      company: "HashiCorp",
      location: "Europe (Remote)",
      salary: "€100k – €140k",
      type: "Remote",
      postedAt: "1 day ago",
      url: "https://www.linkedin.com/jobs",
      logo: "https://logo.clearbit.com/hashicorp.com",
      matchScore: 98,
    },
    {
      id: "do-j2",
      title: "Cloud Infrastructure Specialist",
      company: "AWS",
      location: "Seattle, WA",
      salary: "$150k – $210k",
      type: "Hybrid",
      postedAt: "4 days ago",
      url: "https://www.linkedin.com/jobs",
      logo: "https://logo.clearbit.com/amazon.com",
      matchScore: 96,
    },
  ],
  "Mobile Development": [
    {
      id: "md-j1",
      title: "iOS Engineer (SwiftUI)",
      company: "Snap Inc.",
      location: "Santa Monica, CA",
      salary: "$140k – $190k",
      type: "On-site",
      postedAt: "2 days ago",
      url: "https://www.linkedin.com/jobs",
      logo: "https://logo.clearbit.com/snapchat.com",
      matchScore: 94,
    },
    {
      id: "md-j2",
      title: "Android Developer",
      company: "Spotify",
      location: "Stockholm, SE",
      salary: "800k – 1.1M SEK",
      type: "Remote",
      postedAt: "1 week ago",
      url: "https://www.linkedin.com/jobs",
      logo: "https://logo.clearbit.com/spotify.com",
      matchScore: 91,
    },
  ],
  "Cloud Computing": [
    {
      id: "cc-j1",
      title: "Cloud Solutions Architect",
      company: "Google Cloud",
      location: "Mountain View, CA",
      salary: "$160k – $240k",
      type: "Hybrid",
      postedAt: "3 days ago",
      url: "https://www.linkedin.com/jobs",
      logo: "https://logo.clearbit.com/google.com",
      matchScore: 97,
    },
    {
      id: "cc-j2",
      title: "Digital Ocean Platform Engineer",
      company: "DigitalOcean",
      location: "Remote",
      salary: "$130k – $180k",
      type: "Remote",
      postedAt: "5 days ago",
      url: "https://www.linkedin.com/jobs",
      logo: "https://logo.clearbit.com/digitalocean.com",
      matchScore: 93,
    },
  ],
  "Cybersecurity": [
    {
      id: "cy-j1",
      title: "Security Engineer (Detection & Response)",
      company: "CrowdStrike",
      location: "Austin, TX",
      salary: "$150k – $220k",
      type: "Remote",
      postedAt: "2 days ago",
      url: "https://www.linkedin.com/jobs",
      logo: "https://logo.clearbit.com/crowdstrike.com",
      matchScore: 96,
    },
    {
      id: "cy-j2",
      title: "Product Security Lead",
      company: "Okta",
      location: "San Francisco, CA",
      salary: "$180k – $250k",
      type: "Hybrid",
      postedAt: "4 days ago",
      url: "https://www.linkedin.com/jobs",
      logo: "https://logo.clearbit.com/okta.com",
      matchScore: 94,
    },
  ],
  "UI/UX Design": [
    {
      id: "ui-j1",
      title: "Product Designer",
      company: "Figma",
      location: "San Francisco, CA",
      salary: "$150k – $230k",
      type: "Hybrid",
      postedAt: "1 day ago",
      url: "https://www.linkedin.com/jobs",
      logo: "https://logo.clearbit.com/figma.com",
      matchScore: 98,
    },
    {
      id: "ui-j2",
      title: "Senior UX Researcher",
      company: "Pinterest",
      location: "Remote",
      salary: "$140k – $190k",
      type: "Remote",
      postedAt: "3 days ago",
      url: "https://www.linkedin.com/jobs",
      logo: "https://logo.clearbit.com/pinterest.com",
      matchScore: 92,
    },
  ],
  "Blockchain": [
    {
      id: "bc-j1",
      title: "Solidity Developer",
      company: "Uniswap Labs",
      location: "New York, NY",
      salary: "$160k – $240k",
      type: "Remote",
      postedAt: "2 days ago",
      url: "https://www.linkedin.com/jobs",
      logo: "https://logo.clearbit.com/uniswap.org",
      matchScore: 97,
    },
    {
      id: "bc-j2",
      title: "Protocol Engineer",
      company: "Chainlink",
      location: "Remote",
      salary: "$180k – $280k",
      type: "Remote",
      postedAt: "4 days ago",
      url: "https://www.linkedin.com/jobs",
      logo: "https://logo.clearbit.com/chain.link",
      matchScore: 95,
    },
  ],
  "Game Development": [
    {
      id: "gd-j1",
      title: "Gameplay Engineer (Unreal Engine 5)",
      company: "Epic Games",
      location: "Cary, NC",
      salary: "$150k – $210k",
      type: "On-site",
      postedAt: "1 day ago",
      url: "https://www.linkedin.com/jobs",
      logo: "https://logo.clearbit.com/epicgames.com",
      matchScore: 98,
    },
    {
      id: "gd-j2",
      title: "Graphics Programmer",
      company: "Unity",
      location: "Copenhagen, DK",
      salary: "$130k – $180k",
      type: "Hybrid",
      postedAt: "3 days ago",
      url: "https://www.linkedin.com/jobs",
      logo: "https://logo.clearbit.com/unity.com",
      matchScore: 95,
    },
  ],
};
